apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  labels:
    project: roboshop
    component: payment
    tier: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080
  AMQP_HOST: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    project: roboshop
    component: payment
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: payment
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: app
    spec:
      containers:
      - name: payment
        image: rajesh947/payment:v1
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    project: roboshop
    component: payment
    tier: app
spec:
  selector:   
    project: roboshop
    component: payment
    tier: app    
  ports:
    - protocol: TCP
      port: 8080       
      targetPort: 8080 # container port
  type: ClusterIP