apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        tier: app
    spec:
      containers:
      - name: cart
        image: rajesh947/cart:v1
        envFrom:
        - configMapRef:
            name: cart
namespace: roboshop

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: app
spec:
  selector:   
    project: roboshop
    component: cart
    tier: app    
  ports:
    - protocol: TCP
      port: 8080       
      targetPort: 8080 # container port
  type: ClusterIP