apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql" 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: app
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: app
    spec:
      containers:
      - name: shipping
        image: rajesh947/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping

---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: app
spec:
  selector:   
    project: roboshop
    component: shipping
    tier: app    
  ports:
    - protocol: TCP
      port: 8080       # The port the Service itself exposes
      targetPort: 8080 # container port
  type: ClusterIP