apiVersion: v1
kind: Secret
metadata:
  namespace: roboshop
  name: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: rajesh947/mysql:v1
        envFrom:
        - secretRef:
            name: mysql

---

apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  selector:   
    project: roboshop
    component: mysql
    tier: database    
  ports:
    - protocol: TCP
      port: 3306    # The port the Service itself exposes
      targetPort: 3306 # container port
  type: ClusterIP