apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret
  labels:
    project: roboshop
    environment: dev
spec:
  serviceAccountName: roboshop-mysql-secret-reader
  volumes:
  - name: mysql-secret #shared volume
    emptyDir: {}
  containers:
  - name: mysql-secret
    image: amazon/aws-cli
    command: 
    - sleep
    - "10000"
    volumeMounts:
        - mountPath: /tmp
          name: mysql-secret
    