apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret
  labels:
    project: roboshop
    environment: dev
spec:
  serviceAccountName: roboshop-mysql-secret-reader
  volumes:
  - name: mysql-secret #shared volume
    emptyDir: {}
  containers:
  - name: mysql-secret
    image: amazon/aws-cli
    command:
    - sh
    - -c
    - |
        aws secretsmanager get-secret-value --secret-id roboshop/mysql/root_password --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
    volumeMounts:
    - name: mysql-secret
      mountPath: /tmp