apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: database
    spec:
      volumes:
      - name: mysql-secret #shared volume
        emptyDir: {}
      initContainers:
      - name: fetch-mysql-secret
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id roboshop/mysql/root_password --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp
      containers:
      - name: mysql
        image: rajesh947/mysql:v2
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  selector:   
    project: roboshop
    component: mysql
    tier: database    
  ports:
    - protocol: TCP
      port: 3306    # The port the Service itself exposes
      targetPort: 3306 # container port
  type: ClusterIP