apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  labels:
    project: roboshop
    component: user
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
  REDIS_URL: "redis://redis:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: app
    spec:
      containers:
      - name: user
        image: rajesh947/user:v1

---

apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  selector:   
    project: roboshop
    component: user
    tier: app    
  ports:
    - protocol: TCP
      port: 8080       # The port the Service itself exposes
      targetPort: 8080 # container port
  type: ClusterIP