apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    project: roboshop
    component: redis
    tier: database
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:7.0

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    project: roboshop
    component: redis
    tier: database
spec:
  selector:   
    project: roboshop
    component: redis
    tier: database    
  ports:
    - protocol: TCP
      port: 6379      # The port the Service itself exposes
      targetPort: 6379 # container port
  type: ClusterIP